### ISSUE TITLE
SteamAnalyst Link

### ISSUE THREAD

**Issue by rylinaux** [ncla/LoungeDestroyer#109]
Just as when you hover over an item and you are able to click a link to view the item on the Steam market, it would be useful to have a linked to be able to view it on SteamAnalyst as well.

**Comment by ncla** [comment]
Asking them again, if they do not reply or just say no, I am closing this issue.

http://www.reddit.com/r/steamanalyst/comments/2x7ywx/api_for_developers_links_based_on_item_name/

**Comment by ncla** [comment]
This ain't happening. Basically they won't give the API because they believe it can be monetizable (the data which comes from Steam, and not something they have generated themselves). Also because we are open-source we would be exposing their API by caching it on our server.
