### ISSUE TITLE
When I reload setting page they don't save

### ISSUE THREAD

**Issue by grumd** [ncla/LoungeDestroyer#126]
I change the settings, then reload the settings page and it reverts to default. Settings never save :(

**Comment by birjolaxew** [comment]
Has this happened more than once? Are the settings saved (i.e. setting autobump to enabled actually autobumps your trades), and reset only when loading the settings page?

**Comment by grumd** [comment]
It happens all the time. The settings do work, they still do their job and it only shows the wrong positions in settings page.
More info: most of the settings do save, it's only few of them which don't get saved and are reset upon page reload.
Settings that are getting reset:
Enable auto-betting/-returning/-accept
Show match type and exact time
Use cached item price list
Show trade descriptions
Add preview buttons to trades
Attempt to auto-bump trades every 10 minutes
Notify on queue trade offer:
Notify about items that are going to expire soon:

Still they work, for example, if I check Show match type and exact time to Disabled, it will not show it, but in the settings it will say "Load automatically for upcoming matches + on hover"

**Comment by grumd** [comment]
Sorry, accidentally closed

**Comment by birjolaxew** [comment]
Interesting. Could you go to the settings page (make sure it has reset itself), hit F12, click the "Console" tab, and paste the following code:

```
chrome.storage.local.get("userSettings",function(x){var settings=JSON.parse(x.userSettings), Settings=defaultUser.defaultSettings,outp="";$.each(settings,function(i,v){outp+=i+"="+v+"; ";Settings[i]=v});console.log(outp);outp="";console.log("===");$.each(Settings,function(i,v){if (v){outp+=i+"="+v+"; ";}else{console.error("Falsy setting",i,"=",v)}});console.log(outp);})
```

It'll print a bunch of stuff to console. Post that stuff here. Then change one of the settings that reset themselves, paste that into console again, and post the result here too.

**Comment by grumd** [comment]
Before changing:
VM1375:2 marketCurrency=1; itemMarketPricesv2=2; redirect=1; removeStream=1; delayBotsOff=30000; delayBotsOn=5000; delayRelogError=15000; notifyBots=0; notifyMatches=3; notifyTrades=3; autoDelay=0.1; enableAuto=1; renameButtons=0; useCachedPriceList=0; notifyExpiredItems=2; addTradePreviews=0; notifyTradeOffer=4; showExtraMatchInfo=2; autoBump=1; acceptDelay=30; easterEgg1=1; streamRemove=0; showDescriptions=0; 

After change console says:
Saving user setting [autoBump] to 730

Then I run script again:
VM1387:2 marketCurrency=1; itemMarketPricesv2=2; redirect=1; removeStream=1; delayBotsOff=30000; delayBotsOn=5000; delayRelogError=15000; notifyBots=0; notifyMatches=3; notifyTrades=3; autoDelay=0.1; enableAuto=1; renameButtons=0; useCachedPriceList=0; notifyExpiredItems=2; addTradePreviews=0; notifyTradeOffer=4; showExtraMatchInfo=2; autoBump=730; acceptDelay=30; easterEgg1=1; streamRemove=0; showDescriptions=0; 
(so you can see it saved it)

Then I reload the page and run script again:
VM1415:2 marketCurrency=1; itemMarketPricesv2=2; redirect=1; removeStream=1; delayBotsOff=30000; delayBotsOn=5000; delayRelogError=15000; notifyBots=0; notifyMatches=3; notifyTrades=3; autoDelay=0.1; enableAuto=1; renameButtons=0; useCachedPriceList=0; notifyExpiredItems=2; addTradePreviews=0; notifyTradeOffer=4; showExtraMatchInfo=2; autoBump=730; acceptDelay=30; easterEgg1=1; streamRemove=0; showDescriptions=0; 

So you can see it saves in into local storage but still when I load the page the dropdown list item is set to default. It just doesn't scrap it from local storage

**Comment by birjolaxew** [comment]
Could you try [adding me on Steam](http://steamcommunity.com/id/birjolaxew)?

**Comment by grumd** [comment]
Added.

**Comment by grumd** [comment]
Changed line 28 in options.js to "$(".ld-settings #"+index).val(value);" and it works just fine, thanks birjolaxew!
