### ISSUE TITLE
Force HTTPS on site

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#131]
Lounge site supports HTTPS, might as well take advantage from it.

**Comment by ncla** [comment]
Funnily enough, CSGOLounge HTTPS works fine (with some remote images loading through HTTP though), DOTA2Lounge shits itself however, the stylesheet does not load.

**Comment by birjolaxew** [comment]
With how poorly Lounge is coded in other areas, I wouldn't be surprised if tons of bugs popped up. Could also be a job for HTTPS Everywhere?

**Comment by ncla** [comment]
Yeah, not gonna bother then.
