### ISSUE TITLE
Item groups in inventory

### ISSUE THREAD

**Issue by birjolaxew** [ncla/LoungeDestroyer#133]

**Comment by birjolaxew** [comment]
An implementation of this has been pushed to my fork - going to wait for the greenlight from @ncla and test it some more before creating pull request

**Comment by ncla** [comment]
How does it work? Don't have time to check today.

**Comment by birjolaxew** [comment]
Basically, inventory gets loaded, elements for all custom item groups are created and added to a wrapper element. The item group data is stored internally in `LoungeUser.userSettings.itemGroups`, in the format `{internal-name: {title: "Readable name", items: ["item-name"], priority: 123}}`, where priority indicates what groups it should be placed below (lower priority = higher up, set when saving groups), which is parsed and all items are placed in their respective group element. The items are sortable (again jQuery UI), and can be moved between groups.

**Comment by ncla** [comment]
Are inventory statistics adopting to the inventory groups?

**Comment by birjolaxew** [comment]
Inventory statistics are added before the groups, so they shouldn't be affected. Even then, items are still grandchildren of backpack, so `addInventoryStatistics`'s selector (`#backpack .item`) should still work properly.

**Comment by ncla** [comment]
TO-DO:
Inventory grouping should be game specific
Add option to generate inventory statistics for individual inventory group

**Comment by birjolaxew** [comment]
I consider this closed unless bugs pop up
