### ISSUE TITLE
New "temporarily unavabilable" page

### ISSUE THREAD

**Issue by birjolaxew** [ncla/LoungeDestroyer#134]
Seems to pop up when getting a 502 Bad Gateway error. Should probably redirect this too.

![](http://i.imgur.com/LHtkftX.png)

**Comment by ncla** [comment]
I am not sure if we want to redirect/refresh though, because this is not so annoying as much as the wait.html redirect.

**Comment by ncla** [comment]
Closing this as it seems unnecessary to redirect from this.
