### ISSUE TITLE
View logic separation

### ISSUE THREAD

**Issue by Jakehp** [ncla/LoungeDestroyer#137]
"With this project I want **MVC** and OOP feel in the application."
"Trades, bets, queues, items and so on have their own class and their own seperate file. Those should all be considered as **models** part of application"

View logic, in the form of jquery id and class selectors, are scattered everywhere in all the JS files. I propose we pull all these string literals and put them somewhere outside of the models/etc.

This would make it so if html changes, you only have to change 'view links' in one place, rather than searching across the app and replacing each individual use. It would also make things a bit cleaner rather than string selectors all over the place.

What do you guys think?

**Comment by Jakehp** [comment]
Here's what I'm thinking - https://github.com/Jakehp/LoungeDestroyer/blob/470cca60566e3ef2f96cbe787e0f223403061052/app/domlinker.js

Ideally, we wouldn't be doing any jquery if you truly consider "Trades, bets, queues, items and so on have their own class and their own seperate file. Those should all be considered as models part of application". But this is a start, to separating the view/model coupling.

**Comment by ncla** [comment]
This seems like a really cool idea. This would allow us to define selectors for Dota2Lounge or CSGOLounge specific elements without doing dirty ifelse statements.

Not sure about getClassSelector and getIdSelector, I think just writing a selector itself will be better idea.

**Comment by Jakehp** [comment]
The reason I had getClass/getID is, often in places you will see
document.getElementById()
Which will require no #
But you will also see $()
Which does require #
So I figure allow access to both, and based on what is using the view selector (getEId or $ selectors), get the appropriate string.

**Comment by ncla** [comment]
Don't submit the PR yet though (or do, but will have to merge in manually in the future then). I at least would like to get this in the release after next one if you don't mind.

**Comment by birjolaxew** [comment]
I really like this too - we really haven't had much focus on decent coding practices, and probably have grown a little blind to our faults. Input from someone other than @ncla and me is awesome.

**Comment by Jakehp** [comment]
Just let me know when to submit it and I will.
