### ISSUE TITLE
Stealth mode

### ISSUE THREAD

**Issue by birjolaxew** [ncla/LoungeDestroyer#140]
Implement stealth mode in two variants:

- Weak:
Any server-visible differences (notably HTTP headers) between our users and normal users are hidden.
- Strong: No new elements are added to DOM (alternatively: keep an updatable list of scripts to block, for if they attempt to detect us à la LoungeCompanion)

**Comment by ncla** [comment]
Implement delay randomizer as well. :)

**Comment by birjolaxew** [comment]
Weak mode implemented

**Comment by birjolaxew** [comment]
Going to close this until a need comes up for strong mode
