### ISSUE TITLE
Can't trade with Destroyer on?

### ISSUE THREAD

**Issue by moogel7** [ncla/LoungeDestroyer#143]
Hi, I seem to be unable to complete the trade on CS:GOLounge with the LoungeDestroyer on, any ideas on the fix? o.o Or is that just me?

**Comment by birjolaxew** [comment]
Can you be a bit more specific, possibly with screenshots?

**Comment by moogel7** [comment]
Like, when you are putting a bet in on CSGOLounge with your inventory, I never get a trade offer, CSGOLounge just refreshes the screen, with no trade offer as if it never happened.

**Comment by birjolaxew** [comment]
Can you confirm that you are on 0.8.0.6, and restart the browser before trying again?

**Comment by ncla** [comment]
Assuming the problem is non existed.
