### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Jakehp** [ncla/LoungeDestroyer#148]
Here's what we got http://i.imgur.com/csFz42Z.png

I'll be talking with a GFX bud and we'll post some ideas here.

**Comment by ncla** [comment]
Yup, a much better logo would be needed. :+1:

**Comment by Jakehp** [comment]
http://i.imgur.com/JuRbNUI.png

**Comment by farblood** [comment]
http://prntscr.com/60odte

**Comment by ncla** [comment]
I like it how it looks right now but the CSGL arrow should be perhaps smaller, scaled down.

More feedback from others is welcomed.

**Comment by birjolaxew** [comment]
Agree - really dig the concept, but it should be more clear that that's an arrow.
Suggestions (ignore shitty, shitty design skills): http://i.imgur.com/JfQEfQg.png

**Comment by Stalast** [comment]
@farblood Looks great, the 'LD' should be moved down very slightly as the top left of the L is too close to the outer edge of the shape. The orange 'arrow' shouldn't be floating around the perimeter of the 'D'. It either needs to be encapsulated fully by the arrow or half-on like the 'L'.

**Comment by farblood** [comment]
@Stalast edited it a LITTLE bit. http://prntscr.com/60pfnz

Not sure about the aligning it completely perfectly for each letter, because CSGL arrow isn't simetrical http://prntscr.com/60phic.

@birjolaxew Hmm... Maybe it really should be a little more obvious, but then the icon will lose it's diamond.

**Comment by Stalast** [comment]
@farblood Looks much better, I still think the LD should be shifted down by a few pixels to balance out the vertical volume.

**Comment by farblood** [comment]
@Stalast Do you really think so? For me it's pretty nicely vertically aligned. Anyways, you would be able to see that text only on your chrome extensions page, everywhere else I'm planing to remove it.

**Comment by Stalast** [comment]
@farblood This is my opinion - http://puu.sh/fqXmH/c89324d987.png

**Comment by ncla** [comment]
If anyone is curious how it looks when used within the extension:

![](http://puu.sh/fstp1/a2327be2c2.png)
![](http://puu.sh/fstrV/de6de47b08.png)
![](http://puu.sh/fstuB/226cc013bb.png)
