### ISSUE TITLE
Landing page - general site.

### ISSUE THREAD

**Issue by Jakehp** [ncla/LoungeDestroyer#149]
As mentioned in https://github.com/ncla/LoungeDestroyer/issues/148, we should have a simple 1 page site.

I'd suggest we create a github pages site, which are free. Either...

A) You create a LoungeDestroyer organization (https://github.com/organizations/new), then create a repo under that github org called 'loungedestroyer.github.io'

B) You create a repo under your current account 'ncla.github.io', but then you use your 1 free github pages site for your account.

Read more here - https://pages.github.com/

**Comment by ncla** [comment]
I have a web server where I could host the web site, but we need a domain or sub-domain for that one then.

**Comment by Jakehp** [comment]
Well I think the github pages is a better solution. It's free and can handle any load. It would also update immediately whenever the repo changes (versus you having to manually update, or have some CI update it).

**Comment by Jakehp** [comment]
If you do A or B, I'll start it and submit some PR's.

**Comment by ncla** [comment]
http://ncla.github.io/LoungeDestroyer/
gh-pages branch. Probably should move the website somewhere else but for now you can commit stuff  there.

**Comment by Jakehp** [comment]
WIP - https://github.com/ncla/LoungeDestroyer/pull/159
