### ISSUE TITLE
Why price are not in colour of a item 

### ISSUE THREAD

**Issue by dmgman** [ncla/LoungeDestroyer#162]
Hello sry 4 bad eng.
I try to ask what i need to do to make price a colour of a item, i'm mean immortal=gold/ legendary=pink...
right now thay all white as like common item *((

**Comment by ncla** [comment]
There are currently no options to change that behaviour.

Be care.

**Comment by dmgman** [comment]
ths man. i hope you add this option in some future updates

2015-02-02 20:29 GMT+02:00 ncla <notifications@github.com>:

**Comment by ncla** [comment]
Fixed, the reason this was done is to have to consistent be able to read the market price.

The CSGOLounge rarity still gets a white background because if the item image larger than usual then it covers/blends with the market price.
