### ISSUE TITLE
Auto bump.

### ISSUE THREAD

**Issue by hexenas** [ncla/LoungeDestroyer#176]
Hello i was checking my trades and noticed that it only autobumps every 40 mins (i know it tries every 1 0 minutes but i think they should do autobump like every 10minutes 10~ seconds or so).if theres fix please respond.

**Comment by ncla** [comment]
10 minutes interval is fine and there is no need to do it even faster.

**Comment by hexenas** [comment]
You didnt understand i mean make autobump like 10 second later than now because it only autobumps every 10 minutes and at 30 minute it just doesnt autobump ... i have to wait till 40th minute that it could autobump trade.
