### ISSUE TITLE
Display float value of item under market price

### ISSUE THREAD

**Issue by iGeTT** [ncla/LoungeDestroyer#177]
I wonder if i could make it just for me, but i suck at JS.
The main idea is to display Float Value of the item (from GetPlayerItems/Items/ID/attributes/8) under market price, so people can check item's look without going in-game.
![screenshot_1](https://cloud.githubusercontent.com/assets/2021998/6147933/a50fcabc-b20d-11e4-85be-5bdfd705aa4a.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/2021998/6147934/a5113302-b20d-11e4-8903-f1430c3e7fa4.png)

**Comment by ncla** [comment]
Ugh, this is a feature that only experienced traders would need, so I don't think we would implement this. However, are you asking for someone to code it for you or what?

**Comment by iGeTT** [comment]
It's just a suggestion :)

**Comment by birjolaxew** [comment]
Unlikely to be implemented, mostly because it's rather obscure, but also because it doesn't apply to most items (only applies to those in your own backpack), and is rather problematic to implement.
