### ISSUE TITLE
Auto-return doesn't automatically open the offer

### ISSUE THREAD

**Issue by brampower** [ncla/LoungeDestroyer#178]
Hey guys,

First of all, great update!

However, it broke my 'Auto-return' function. Once I click on 'FUCKING REQUEST RETURNS' it goes through the whole thing, it all works. However, when I finally do get an offer, in the bottom right it will say something along the lines of 'Waiting for offer...'

Now, it just stays on that page. Nothing else happens. If I then manually refresh the page, the notification in the bottom right will actually have the 'Go to offer' button and LoungeDestroyer will automatically do it's thing. It's just that one refresh that I have to do every single time.

I have already tried to reinstall the addon but that did not work, unfortunately.

**Comment by birjolaxew** [comment]
Is this reproducable (i.e. does it happen all the time/can you reliably make it happen)? Have you tried disabling LD (at chrome://extensions) and verifying that it works without it enabled? If so, could you [add me on Steam](http://steamcommunity.com/id/birjolaxew)?

**Comment by brampower** [comment]
Well, isn't that interesting. I never thought to try it without LoungeDestroyer disabled, and you're right; it doesn't work.

I assume it has something to do with the JavaScript. Chrome users have reported problems using CSGOLounge because of some JavaScript errors. I hope they fix them soon; what's strange is that it does not seem to affect everybody, though. My Chrome is updated.

Anyway, thanks for your help!

**Comment by birjolaxew** [comment]
Awesome, thanks for confirming.

If you can reproduce it, I'd love to try to debug it, so we can report it to Lounge and (hopefully) have them fix it - if you have a few minutes to spare, and want to help out, add me on Steam (link above).

**Comment by birjolaxew** [comment]
Was caused by [anti-anti-loungecompanion](http://www.reddit.com/r/csgobetting/comments/2hjhp6/if_you_dont_want_to_support_childish_csgl_admins/), which cleared the `setInterval(function() { [...] queueCheck(); }, 12000);` interval.

**Comment by ncla** [comment]
#blamekinsi

**Comment by brampower** [comment]
My bad, guys. thanks to birjolaxew for the huge help! :+1:
