### ISSUE TITLE
Adding an icon to matches that you have a bet on?

### ISSUE THREAD

**Issue by Buzzbya** [ncla/LoungeDestroyer#184]
Something that i find really cumbersome with CSGOLounge is i often forget which matches ive bet on, and going back and forth between my bets and the front page, or checking every match, can take a long time, esp if its under heavy load. I think it would be very nice to have a reminder on which matches I've bet on.

**Comment by birjolaxew** [comment]
This is kind of iffy, but I implemented it none-the-less in 79a0bc0. It's disabled by default. Thanks for the suggestion, it'll be in the next release.
