### ISSUE TITLE
Choice between profane and non-profane text

### ISSUE THREAD

**Issue by Doggie52** [ncla/LoungeDestroyer#187]
Loving this extension but I'd love to be able to choose whether my buttons say *FUCKING REQUEST RETURNS* or just *Request Returns*. I guess it was a funny thing when you made it, but it's a bit childish and I'd love to have it removed (or at least have the ability to choose to remove it).

**Comment by ncla** [comment]
Profanity option in settings.

**Comment by Doggie52** [comment]
It should be disabled by default. There is no reasonable scenario when someone would want it enabled, let alone enabled by default.

**Comment by birjolaxew** [comment]
> It should be disabled by default.

No.

**Comment by ncla** [comment]
It is my 'touch' for this extension (or user-script when I first created it), and it is quite appropriate considering how many times you have to press the button to actually get your bet in.

Another reason to consider why we are replacing the text is that if there was no text replaced the user might be confused as to how the extension actually works when using it for first time.

We are not changing it, we are not professionals. If you can't handle knowing fact that this extension has a 'F' word in the extension, don't use it.

**Comment by Doggie52** [comment]
Fair enough, thank you for taking the time to explain your opinion!
