### ISSUE TITLE
Replace the annoying beep sound (when trade offer has been received) with something else (or just disable it)

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#188]
It think we can all agree on this.

**Comment by birjolaxew** [comment]
Best way to do it would probably be to catch the request for the audio file in transit, and redirect it to a custom one using `chrome.webRequest.onBeforeRequest`. Possibly allow users to change it?

**Comment by birjolaxew** [comment]
Implemented in 8489dc6
