### ISSUE TITLE
LoungeDestroyer API for item price list

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#19]
So at the moment the Steam market prices loading is not very performance friendly, for every item there is you need one request to Steam market API. Instead, we could have our own API on a web server that stores all CS:GO market item prices, it would return all CS:GO Steam market values at once. Then every hour the extension from background tasks puts new market prices in local storage.

Only thing to do is write the web application itself, or find already existing solution written and just reuse that.

**Comment by Jakehp** [comment]
Is this still something that wants to be done?

**Comment by ncla** [comment]
Amusing.

http://stackoverflow.com/questions/28835050/deserialize-and-access-csgo-json-array-in-vb-net
http://www.reddit.com/r/Steam/comments/2l1o3l/steam_api_lowest_market_price_xpost_from_rdevsteam/
http://projects4freelance.com/projects/steam-trade-bot-integrated-with-xenforo-forum-612811.html

**Comment by Wysywyger** [comment]
apologies for necroing this, I am also looking to write a code that will fetch the market data for all available items. I have looked at what's available on GitHub but it seems all to fetch the data for single items. Is there something that does it for all items for a game?

**Comment by ncla** [comment]
There is no easy way, sadly.

**Comment by xscence** [comment]
http://api.steampowered.com/ISteamEconomy/GetAssetClassInfo/v0001?key={APIKEY}&format=json&language=en&appid=730&class_count=1&classid0=350539070

Is there another alternative to get all cs:go weapon skins not ony by one ?

**Comment by Andrej730** [comment]
@xscence 
All i know - you can take some classids from here 
```
http://api.steampowered.com/ISteamEconomy/GetAssetPrices/v0001?format=json&language=en&appid=730&key={api_key}
```
and use them like this

```
http://api.steampowered.com/ISteamEconomy/GetAssetClassInfo/v0001?key={api_key}&format=json&language=en&appid=730&class_count=91%27&classid0=992003612&classid1=992003613&classid2=927007517&classid3=721248158&classid4=638243112&classid5=613589848&classid6=360448780&classid7=259019412&classid8=186150630&classid9=341265706&classid10=191923205&classid11=186150629&classid12=506856209&classid13=506856210&classid14=613589849&classid15=613589850&classid16=613589851&classid17=613589852&classid18=613589853&classid19=613589854&classid20=613589855&classid21=613589856&classid22=613589857&classid23=613589858&classid24=613589859&classid25=613589860&classid26=613589861&classid27=613589862&classid28=613589863&classid29=613589864&classid30=613589865&classid31=613589866&classid32=615451613&classid33=619637866&classid34=619637867&classid35=619637868&classid36=619637869&classid37=619637870&classid38=619637871&classid39=619637872&classid40=619637873&classid41=619637874&classid42=625567400&classid43=625567401&classid44=625567402&classid45=625567403&classid46=625567404&classid47=625567405&classid48=667021859&classid49=667021860&classid50=667021861&classid51=667021863&classid52=667021864&classid53=667021865&classid54=667021866&classid55=667021867&classid56=667021868&classid57=667021869&classid58=667021870&classid59=667021871&classid60=667021872&classid61=667021873&classid62=783092523&classid63=783092524&classid64=783092525&classid65=783092526&classid66=783092527&classid67=783092528&classid68=783092529&classid69=783092530&classid70=783092532&classid71=783092533&classid72=783092534&classid73=783092535&classid74=783092536&classid75=783092537&classid76=783092538&classid77=783092539&classid78=783092540&classid79=945464709&classid80=945464710&classid81=945464711&classid82=945464712&classid83=945464713&classid84=945464714&classid85=945464715&classid86=945464716&classid87=945464717&classid88=945464718&classid89=945464719&classid90=903185406%27
```
But, anyway, its not full list of items.

**Comment by xscence** [comment]
then how most of the bet websites have all items ? And thanks for your response!
