### ISSUE TITLE
Autobetting broken for tournament predictions

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#195]
https://www.reddit.com/r/csgolounge/comments/2ymtxd/im_having_a_problem_betting_on_the_katowice/?sort=confidence

**Comment by birjolaxew** [comment]
Going to need a new tournament to come up before I can debug this.

**Comment by ncla** [comment]
@birjolaxew there is one going atm on CSGOlounge

**Comment by birjolaxew** [comment]
Fixed in #189
