### ISSUE TITLE
Total item value not shown in currency set

### ISSUE THREAD

**Issue by Th0masR0ss** [ncla/LoungeDestroyer#198]
![Screenshot](http://i.imgur.com/OIvfb3r.png)

As seen in the above screenshot, I have my currency set to Canadian dollars, however, the "Total item value" section is in (presumably) US dollars.

**Comment by Th0masR0ss** [comment]
Oh. Ha! You already fixed it. Thanks!

**Comment by ncla** [comment]
The timing is real lol.

**Comment by Th0masR0ss** [comment]
Yeah, exact same commit times!
