### ISSUE TITLE
Bookmark support.

### ISSUE THREAD

**Issue by Funergy** [ncla/LoungeDestroyer#204]
If I press the bookmark it goes to csgolounge but without the theme.

**Comment by ncla** [comment]
I just tried it myself and could not reproduce the issue. Are you using CleanLounge theme or testing your own theme?

**Comment by birjolaxew** [comment]
Couldn't reproduce here either.

**Comment by ncla** [comment]
I will reopen this if the bug is reproducible.

**Comment by Funergy** [comment]
https://youtu.be/c68B2Oip_Rs

**Comment by Funergy** [comment]
Here is how I do it

**Comment by Funergy** [comment]
Okay. I changed the bookmark to https://csgolounge.com and it worked now.
The problem is it doesnt work with www.csgolounge.com
