### ISSUE TITLE
WWW support

### ISSUE THREAD

**Issue by Funergy** [ncla/LoungeDestroyer#205]
So I had the problem with bookmarks. But this isnt the case anymore. It was I had set the url to www.csgolounge.com
and not 
https://csgolounge.com

with the www it doesnt show the theme.

**Comment by ncla** [comment]
CSGOLounge rarely themselves refer with a www in front of them. In fact, if you log in it will redirect back to regular csgolounge.com without the www in front.

The whole extension does not work, not just the theme. 

Not really an issue.
