### ISSUE TITLE
When editing themes CSS, it should display the originally inputted CSS, not parsed CSS

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#218]
Currently if user saves the CSS and if the user were to edit the CSS again the user would see !important'ified CSS.

**Comment by birjolaxew** [comment]
This would require us to store the originally inputted CSS, effectively multiplying the used RAM by a factor of 2-3.

**Comment by ncla** [comment]
Fuck it.

You are right.

This is not worth the effort.
