### ISSUE TITLE
Chrome no longer sets Origin header for background script requests?

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#220]
Can someone confirm that Chrome no longer sends Origin header for requests from background scripts? @birjolaxew 

Version 41.0.2272.76 Built on Ubuntu 14.04, running on elementary OS 0.3 (64-bit)

Does not send Origin header.

**Comment by birjolaxew** [comment]
Verified on version 42.0.2311.90, Windows 8.

**Comment by ncla** [comment]
No, I just noticed this today when looking at request headers. We should still send authentic requests for Lounge stuff though.
