### ISSUE TITLE
LoungeDestroyer features that interact with the site are broken

### ISSUE THREAD

**Issue by WolfrostHub** [ncla/LoungeDestroyer#224]
1. CSGO Lounge.
2. Version 42.0.2311.152 running on Windows 7 Ultimate Edition.
3. It happens every time when I do a trade search.
4. I expect LoungeDestroyer to show the "Preview" button on the right of any trade.
5. The button doesn't show up.
6. Go on "Search" label. Click. Do a search. After the page loads go on the second page. Then the bug starts.
7. All my settings are default (I've resetted them)
8. http://imgur.com/8yEI0Nm
9. http://pastebin.com/yBe5Y1KV
10. http://pastebin.com/txDk4mXH

**Comment by ncla** [comment]
http://www.reddit.com/r/loungedestroyer/wiki/index#wiki_submitting_bug_reports

Might be however related to existing major bug that other people already have reported. http://www.reddit.com/r/loungedestroyer/new

**Comment by WolfrostHub** [comment]
In the subreddit I don't see any thread related to my bug...

**Comment by ncla** [comment]
Then please follow the instructions from the first link I sent you.

**Comment by WolfrostHub** [comment]
Ok sorry

**Comment by WolfrostHub** [comment]
Done

**Comment by ncla** [comment]
Yeah, this issue is related to other issues reported on the subreddit, 0.8.3.2 is pending review currently on the Chrome store, so wait for that.

**Comment by ncla** [comment]
Gonna keep this open until 0.8.3.2 has been accepted..

**Comment by WolfrostHub** [comment]
How much time can take the release of 0.8.3.2?

**Comment by ncla** [comment]
We don't know.
