### ISSUE TITLE
Game type check for auto-betting breaks when betting from HTTPS

### ISSUE THREAD

**Issue by birjolaxew** [ncla/LoungeDestroyer#239]
All checks (eg. in `bet_bg.js`) should check for `://<url>`, not `http://<url>` - possibly other things should be changed to support HTTPS to a level where important features don't break.

**Comment by ncla** [comment]
Cloudflare gives free HTTPS, api.ncla.me could be switched to https as well.

**Comment by ncla** [comment]
@bet_bg.js
```
    var game = sender.url.indexOf('http://csgolounge.com/') === 0 ? 0 :
               sender.url.indexOf('http://dota2lounge.com/') === 0 ? 1 :
               -1;
```

**Comment by ncla** [comment]
Should fixed here
https://github.com/ncla/LoungeDestroyer/commit/0eebad6ce20c42f1a01b1e719694dbe8896c43d6
