### ISSUE TITLE
Sorting Feature

### ISSUE THREAD

**Issue by TehGrumpyGamer** [ncla/LoungeDestroyer#245]
Hello - I apologize if this is not the right place for feature requests, please point me in the right direction if so!

Would it be possible to implement some kind of sorting feature where you could sort by value of the skin ascending or descending?

**Comment by ncla** [comment]
Hello,

Most of the suggestions are written on our subreddit over here https://www.reddit.com/r/loungedestroyer/

The GitHub however is only for issues/code related things as feature requests will only clutter the issues page.
