### ISSUE TITLE
Bet history NaN

### ISSUE THREAD

**Issue by 1e4** [ncla/LoungeDestroyer#249]
As you can see in the image most of my bet history is NaN, I assume that's from the latest update?

http://i.imgur.com/ULlZA0z.png

**Comment by ncla** [comment]
Yes, I assume you don't have cached item price list enabled and item prices loaded automatically?

**Comment by 1e4** [comment]
Item prices are loaded automatically yes, i cached the item price but no change

**Comment by ncla** [comment]
What's your setting for 'Show total won/lost bet value column for each match in bet history'?

**Comment by ncla** [comment]
Oh I know, press 'Re-fetch item price list for cache' button and see if its fixed.

**Comment by 1e4** [comment]
Sorry, been away this week, yes that worked, it seemed I needed to select the option to use cached prices, and not just click the button dammit.

In other news is there any ideas to add a tally of total won/loss throughout your whole betting history?

**Comment by ncla** [comment]
You mean like total of totals? That wouldn't be accurate anyway.

**Comment by 1e4** [comment]
Yeh, why wouldn't it be accurate? It would at least be a good estimation no?

**Comment by ncla** [comment]
Yeah, I am saying inaccurate because it is using current market prices, instead of prices that were back then, similarly to what LoungeStats does.

**Comment by 1e4** [comment]
Ah fair enough, I haven't developed any extentions for chrome, so how hard would it be to just total them up? Surely the prices can just be incremented (var won, loss, total) when they are gotten from the market?

**Comment by ncla** [comment]
It's an easy thing to implement.

**Comment by 1e4** [comment]
Looking forward to see if it will be added then :)
