### ISSUE TITLE
Request returns

### ISSUE THREAD

**Issue by 1e4** [ncla/LoungeDestroyer#250]
Hi there,

Is it possible to extend this plugin to allow for auto request items? As far as I know, all that needs to happen is a GET request is sent to http://csgolounge.com/ajax/postToReturn.php depending on the response depends if the user can return the items.

**Comment by ncla** [comment]
That's already the case. :)

**Comment by 1e4** [comment]
@ncla how do you mean? You can already do it?

**Comment by ncla** [comment]
Yes.
![](http://i.imgur.com/g8U1d8Z.png)

**Comment by 1e4** [comment]
I saw that, couldn't work out which one only has request return, as I don't fancy auto betting ^_^

**Comment by ncla** [comment]
Yeah, we don't have separate option for it atm.

**Comment by 1e4** [comment]
Ah, well that would be a great addition! :) Good job so far
