### ISSUE TITLE
Preview Button CS:GO Lounge

### ISSUE THREAD

**Issue by ka3ka91** [ncla/LoungeDestroyer#261]
Why you guys removed cooles thinng in ur extention ? :(( Trade descriptions arent good enough. Are there any possible way to change it back ?

**Comment by ncla** [comment]
You can download older version of LoungeDestroyer from [here](https://github.com/ncla/LoungeDestroyer/releases). We removed because the extra trade/Steam info we load in justifies the removal of preview button because it had the same information anyway.
