### ISSUE TITLE
Auto-betting / -return / -accept functionality

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#27]

**Comment by ncla** [comment]
Captchas on trade offers, woooo, yay!

**Comment by ncla** [comment]
They changed their shitty captcha to reCAPTCHA, now we could just easily click on 'I am not a robot' circle and accept offer.

**Comment by birjolaxew** [comment]
Fucks sake, I had just broken their captcha too...

**Comment by ncla** [comment]
Yeah, it looked so easy to break with open libraries on GitHub.

**Comment by ncla** [comment]
I am just gonna close this issue and create a separate issue for captcha issue.
