### ISSUE TITLE
Better .userBetted indicator

### ISSUE THREAD

**Issue by MarekMaras** [ncla/LoungeDestroyer#270]
I suggest to add a better indicator for betted or not.
Right now, I grabbed your indicator settings / HTML Tags and styled my css via custom injected css:

    .ld-bet-teamleft .matchheader, .ld-bet-teamright .matchheader {    
        background: #007700;
        color: black;
    }

Looking like that:
http://take.ms/eMael

I guess, not tested, just pseudo code, it would work with .css() instead or additional to prepend(); in here:

    if (this.userBetted === false && ['1', '3'].indexOf(LoungeUser.userSettings.showBettedIndicatorv2) !== -1) {
        $(matchHeaderBlock).prepend('<span class="bettedIndicator">✘</span> ');
    }

    if (this.userBetted === true && ['2', '3'].indexOf(LoungeUser.userSettings.showBettedIndicatorv2) !== -1) {
        $(matchHeaderBlock).prepend('<span class="bettedIndicator">✔</span> ');
    }  
  
Or just make an optional setting with a colorpicker.

**Comment by ncla** [comment]
Hello,

Thanks for the suggestion, but I am not quite sure what you are going for. CleanLounge is a completely separate thing from LoungeDestroyer, so any issues with any theme styling is not an issue with the core of LoungeDestroyer. CleanLounge has its own separate repository over here https://github.com/farblood/CleanLounge/

Suggestions/feedback/objective criticism you can write him personally on Reddit /u/farblood or on our sub-reddit /r/loungedestroyer.

**Comment by MarekMaras** [comment]
I'm not sure if it's a theme option, but I think the indicator for betted matches is in the LoungeDestroyer settings, if I'm not wrong. Isn't it?
It's an option to color the matchheader on the startpage if you have a bet on this match or not. I like to ahve a colored matchheader rather than and icon.
Just a suggestion, if not useful or necessary, please delete! :)

**Comment by ncla** [comment]
By default LoungeDestroyer does not style anything, it just appends information and features. Only case where we do style stuff is our own appended elements.

It is up to theme creators, or you (if you want to use 3rd party styling extensions), to style it however you please. I don't see this specific, niche suggestion being worth implementing, which if we were to, would please a very small fraction of users.
