### ISSUE TITLE
GlassLounge Theme Breaks Disqus

### ISSUE THREAD

**Issue by SlipperyNipple** [ncla/LoungeDestroyer#271]
Pretty much the title. If you click on someone's avatar to view their profile under csgolounge's dicuss tab, it breaks the disqus sidebar. Here is an image of it https://imgur.com/O3KuQZ6. Thanks in advance. :+1:

**Comment by ncla** [comment]
Thanks for reporting the bug, subscribe to this issue instead if you want to know when it's fixed.
https://github.com/farblood/CleanLounge/issues/17
