### ISSUE TITLE
Difficulties opening settings pages

### ISSUE THREAD

**Issue by ncla** [ncla/LoungeDestroyer#278]
https://www.reddit.com/r/loungedestroyer/comments/3r7xpv/cant_access_settings_page_from_opera/

**Comment by master94ga** [comment]
I don't think this is a real bug, I think that this is a problem of installation of the extension to opera because if you watch the screen also the icon is missing.
Installing the extension from source via developer mode of opera you don't have any bug or missing file.

**Comment by ncla** [comment]
Yeah I have no idea, haven't touched LoungeDestroyer on Opera ever, will have to do towards Firefox Web Extension API release.

**Comment by ncla** [comment]
Cannot reproduce.
