### ISSUE TITLE
Show item information above the mousecursor

### ISSUE THREAD

**Issue by mLgz0rn** [ncla/LoungeDestroyer#299]
Hello!
Would it be possible to make item information show above the mousecursor/item instead of below when hovering over an item?

The reason why i'm asking is because, if I look under "my profile" and point the mouse at the last item there, the information will not show up properly.
And it will "extend" the page.
So the only way to view the information, is by scrolling while having the cursor on the item, that will bring up the information, but if I remove the cursor from the item the page will then "contract" again back to how it was before.

If have taken 3 screenshots here so you can see what I mean http://imgur.com/a/J8klR

**Comment by ncla** [comment]
Hello,

CleanLounge fixes this problem partly (by padding the whole body down by 150px). Otherwise it is an issue with Lounge styling which I don't think we want to fix.

**Comment by voltij** [comment]
@mLgz0rn narrow your window to make the "right" half of the webpage show under the "left" half.
