### ISSUE TITLE
HTTP Error #503 causes autoreturning to hang indefinitely

### ISSUE THREAD

**Issue by voltij** [ncla/LoungeDestroyer#306]
When i get error message of 

"There was an error when accepting trade offer, HTTP Status code #503"

no further action is done by LD and the time "Last Message (XXX.XXs)" just keeps increasing.

So this breaks the autoreturning cycle.

Every other error eventually cycles back to the "autoreturning items" phase.

**Comment by voltij** [comment]
Not the exact issue as described but,

while trying to claim returns without a SessionID the following occured:

http://i.imgur.com/33dZKhz.png

1. Request returns
2. LD autoretry
3. CSGL puts me in queue
4. CSGL sends trade offer
5. LD attempts to get SessionID and receives 503
6. Hang indefinitely.
7. At this point I manually accepted the trade offer
8. The LD window stating "Nothing has happend yet, fetching Session ID cookie now" persisted even after manual trade offer accept AND /mybets page refresh (showing 0 items in requested returns section)

**Comment by ncla** [comment]
Have not heard complaints of this error anymore. Closing.

**Comment by ncla** [comment]
>POST https://steamcommunity.com/tradeoffer/960452392/accept 503 (Service Unavailable)l.cors.b.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4(anonymous function) @ bet.js:511
>bet.js:547 AUTOACCEPT :: Error accepting trade 503 error
>VM114:1 Uncaught SyntaxError: Unexpected token <

This happens when Steam is experiencing problems. On error we try to parse response as JSON (that's what Steam does), and that errors out as the result.

```
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;30&#46;909b7b5c&#46;1452981516&#46;78670db
</BODY></HTML>
```
