### ISSUE TITLE
Auto-detect currency ?

### ISSUE THREAD

**Issue by Outpox** [ncla/LoungeDestroyer#32]
Just an idea I had, since I'm switching between LD version (new commits, etc) I had to change the default currency every time since mine isn't dollar but euro. After a quick search on google I come with this:  
```html
<script type="text/javascript">
 var userLang = navigator.language || navigator.userLanguage; 
 alert ("The language is: " + userLang);
 </script>
```
Then save the currency for countries:

```javascript
var countryCurrency = {
  dollar: 'us',
  euro: {'fr', 'de', 'es', 'it', ...},
  gbp: 'uk',
  ruble: 'rus'
}  
```
This way it would be possible to have the good currency by default ?
That's just a tough/idea, obviously not a priority :-)

**Comment by ncla** [comment]
Closing this as neither me on birjolaxew has showed interest in this.
