### ISSUE TITLE
Can't load betting history.

### ISSUE THREAD

**Issue by EricGrus** [ncla/LoungeDestroyer#325]
Every time I try to load my betting histroy it I get and error that says "(1) Error(20) fetching item data("Any Item"). It happens sometimes, Please try refreshing. The items it shows i lost earlier in a bet.

Image of Error: https://gyazo.com/aaffd6df61049d178b0520cf7c08912f

Thank you

**Comment by ncla** [comment]
This is not LoungeDestroyer, and I don't know what this extension/script is in the screenshot. Can't help.
