### ISSUE TITLE
[Request] Button to scroll down the page to bets

### ISSUE THREAD

**Issue by MorphineBear** [ncla/LoungeDestroyer#338]
Can you add back the button that scrolls up/down the page for trades or bets? The current way CSGO Lounge works is annoying on smaller resolution sizes; typically on a larger display or full screen, it'll add a second column for betting. On smaller resolution sizes it'll just have one column. After refreshing the page every so often, you will see why it's annoying having to scroll down when there's only one column.

**Comment by ncla** [comment]
I don't quite understand you. The buttons for scrolling to bets/trades sections are still there.

**Comment by MorphineBear** [comment]
Is it? I don't see it on my screen at all.
![loungedestroyer](https://cloud.githubusercontent.com/assets/9476380/14330636/45d6a7da-fbf6-11e5-8d71-2a21cef17ae1.PNG)

**Comment by ncla** [comment]
You are using GlassLounge theme.
