### ISSUE TITLE
GlassLounge theme: some objects overlap

### ISSUE THREAD

**Issue by Nuc1eoN** [ncla/LoungeDestroyer#340]
Main page with GlassLounge theme:
![overlap](https://cloud.githubusercontent.com/assets/2538022/14229245/fcabf9d0-f92e-11e5-8a63-8238b99ddc06.PNG)

My reso: 1024*1280

**Comment by ncla** [comment]
https://github.com/YesBacon/LoungeDestroyer-GlassLounge use this repo instead for issues and code. Feel free to contribute.
