### ISSUE TITLE
CleanLounge Night theme: Make trades more distinguishable from each other

### ISSUE THREAD

**Issue by Nuc1eoN** [ncla/LoungeDestroyer#341]
Just look at this screenshot:
![unstructered](https://cloud.githubusercontent.com/assets/2538022/14229266/d70431b0-f92f-11e5-94f6-b5f073c9eee2.PNG)
There's no way to know which boxes beling to which trade. I'd suggest to add a wrapping box around every trade create structure. GlassLounge already has this layout:
![structure](https://cloud.githubusercontent.com/assets/2538022/14229273/237653fc-f930-11e5-80a1-fd341a6be2cd.PNG)
Should be a trivial fix :)

**Comment by ncla** [comment]
Use
https://github.com/farblood/CleanLounge/issues to report bugs related specifically for this theme
https://github.com/ncla/CleanLounge for actual code

Feel free to make a contribution.
