### ISSUE TITLE
Redundant entry: "Show Steam market price"

### ISSUE THREAD

**Issue by Nuc1eoN** [ncla/LoungeDestroyer#342]
The entry "Show Steam market price" seems to be completely redundant if someone has "MARKET PRICES ON ITEMS" set to on:
![steamprice](https://cloud.githubusercontent.com/assets/2538022/14229346/e935a092-f931-11e5-8d8a-5760dd9d76a2.PNG)
The only valid argument to leave it may be the "refresh" functionality of it, but that's kinda a rare case and not very evident. If this functionally is desired, I'd rather add some kind of refresh-button to the pop-up menu, or a text showing "refresh price" instead.

**Comment by ncla** [comment]
It serves as a thing to double check the price before trading, especially if user has enabled cached price list, then the price might even be priced incorrectly.

**Comment by Nuc1eoN** [comment]
Yes but as I said, it would make much more sense to rename it to "Refresh/Reload Steam market price" in this case. Otherwise this isn't self-evident at all.

**Comment by ncla** [comment]
IIRC we already had the word 'refresh' used for that button, but it was changed to 'Show'. In all cases (when there is no price, when price is cached, when the price is outdated, when the price failed to load), I don't see a problem in how it is currently is worded.

Regarding about making it as a refresh button, or cutting down on the specificity: bad UX. LoungeDestroyer deals with betting values in the item containers as well, so having just 'Refresh price' won't be self-evident as to what it does, until user tries of course.
