### ISSUE TITLE
Suggestion: When click open to steamanalyst of that object

### ISSUE THREAD

**Issue by xtreameprogram** [ncla/LoungeDestroyer#344]
I thought it would be nice if that when a user clicked on an object, it would take them to steam analyst giving them a detailed description and etc. I already built this extension(https://github.com/xtreameprogram/SteamAnalyst-Lookup), but I thought if added here, it would be more useful.

**Comment by ncla** [comment]
Apologies for late reply.

We will have something else in place for that later in coming months you can look forward to. We don't really want to support site like SA.
