### ISSUE TITLE
Auto-bump not working due to incorrect redirect to HTTPS

### ISSUE THREAD

**Issue by mocbuhtigsptth** [ncla/LoungeDestroyer#351]
Hello, loungedestroyer stopped pick up deals on dota2lounge. Can you help me?

**Comment by ncla** [comment]
Yes. I will need more information about the issue though.

**Comment by mocbuhtigsptth** [comment]
Dota2 Lounge

Version 0.9.5.0, Windows 10 home (64-bit)

http://dota2lounge.com/mytrades

http://s018.radikal.ru/i510/1701/09/13b49752dfd8.png

http://s019.radikal.ru/i644/1701/64/e01aa84d601a.png

http://s020.radikal.ru/i714/1701/0c/61a3193b6f10.png

http://s013.radikal.ru/i324/1701/70/cd0f4b3027d9.png

**Comment by mocbuhtigsptth** [comment]
Mixed Content: The page at 'https://dota2lounge.com/mytrades' was loaded over HTTPS, but requested an insecure mytrades:1 
image 'http://i.imgur.com/MwMhPlR.jpg'. This content should also be served over HTTPS.
Failed to load resource: the server responded with https://api2.ncla.me/api/items/name/Weather%20Moonbeam/price?appid=570 
status of 404 ()
DevTools failed to parse SourceMap: https://dota2lounge.com/css/materialize.css.map

**Comment by ncla** [comment]
That's all I need. I was able to replicate the issue and a fix will be coming soon.

**Comment by mocbuhtigsptth** [comment]
if you need something else write me

**Comment by ncla** [comment]
You can update your extension now. It should be fixed.
