### ISSUE TITLE
User Stats under the name

### ISSUE THREAD

**Issue by UgaBugaBoo** [ncla/LoungeDestroyer#7]
This feature already exist in an extension for D2L 
Extension Link:
Preview :
![screencapture-dota2lounge-com](https://cloud.githubusercontent.com/assets/7885525/3890720/5da3de78-2222-11e4-8297-59e2df723f1b.png)

It will beamazing if it can be ported to CSGL too :+1:

**Comment by Jakehp** [comment]
This is kinda nifty.
